### PR TITLE
Fix for issues #18 and #19

### PR DESCRIPTION
**Pull request by ellesmith88**
Added a "scan_metadata" section to the character JSON files, also only calculates min and max if mode is "full".

### CODE REVIEW

**Comment by agstephens** [comment]
@ellesmith88: looks good :-)
Please move the `location` argument after `var_id` in the call to `scan_datasets`. Once that is done I am happy with it. Thanks

**Comment by ellesmith88** [comment]
@agstephens is this to be after `ds_ids`? `scan_datasets` doesn't have `var_id` as far as I can tell.

**Comment by agstephens** [comment]
> @agstephens is this to be after `ds_ids`? `scan_datasets` doesn't have `var_id` as far as I can tell.

@ellesmith88 , yes, sorry, my mistake. Thanks

**Comment by ellesmith88** [comment]
@agstephens  `def scan_datasets(project, mode, location, ds_ids=None,  paths=None, facets=None, exclude=None)`

For `scan_datasets` above I can't move `location` after `ds_ids` as it's not a keyword argument.

Maybe you meant `scan_dataset`? Or I'm just confused..!

**Comment by agstephens** [comment]
@ellesmith88 , I think I'm getting confused. That is a very good point. Leave it as is for now. Sorry for the confusion.

**Pull request merged**
