### PR TITLE
added in numpy.float32 option when extracting character

### PR DESCRIPTION
**Pull request by ellesmith88**
Fixes issue when scanning some CORDEX data.

### CODE REVIEW

**Comment by agstephens** [comment]
@ellesmith88 well done for picking this up. I see that the float64 is recorded as a float whereas you are converting the float32 to a string. A couple of thoughts:

1. Should we treat all float types the same - either as floats or strings? 
2. Can we check for a generic numpy float base type using 'isinstance'? Then only one check would deal with all of them?

**Comment by agstephens** [comment]
@ellesmith88 , this kind of introspection in the inheritance tree should help us devise checks at the right level:

```
>>> import numpy as np
>>> n64 = np.float64(1)
>>> n32 = np.float32(1)

>>> n64
1.0
>>> n32
1.0
>>> import inspect

>>> # This next bit tells you the class inheritance tree for `np.float64` - its neat...
>>> inspect.getmro(np.float64)
(<type 'numpy.float64'>, <type 'numpy.floating'>, <type 'numpy.inexact'>, <type 'numpy.number'>, <type 'numpy.generic'>, <type 'float'>, <type object'>)

>>> isinstance(n64, np.floating)
True
>>> isinstance(n32, np.floating)
True
>>> i16 = np.int16(1)
>>> i16
1
>>> isinstance(i16, np.floating)
False
>>> isinstance(i16, np.number)
True
>>> isinstance(n64, np.number)
True
```

So, maybe we can use a couple of checks at this level to test for different types when characterising.

**Comment by ellesmith88** [comment]
@agstephens I didn't catch on that I was converting to a string - thought I was just reducing the decimal places but can see now that's not the best way to do it.  I'll have another go with your suggestion above.

**Comment by ellesmith88** [comment]
@agstephens Updated this PR

**Comment by agstephens** [comment]
@ellesmith88 : Looks spot-on!

**Pull request merged**
